// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $cart from "./routes/cart.tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $products_meal_ from "./routes/products/[meal].tsx";
import * as $AddProduct from "./islands/AddProduct.tsx";
import * as $Cartnum from "./islands/Cartnum.tsx";
import * as $SubProduct from "./islands/SubProduct.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/_middleware.ts": $_middleware,
    "./routes/cart.tsx": $cart,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/products/[meal].tsx": $products_meal_,
  },
  islands: {
    "./islands/AddProduct.tsx": $AddProduct,
    "./islands/Cartnum.tsx": $Cartnum,
    "./islands/SubProduct.tsx": $SubProduct,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
